/***********************************************
 *  Aisha S. Khalif
 * 32381361
 * ICT 306
 ***********************************************/ 

package familytree;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

public class FamilyTreeGUI extends javax.swing.JFrame {

    /**
     * Creates new form FamilyTreeGUI
     */
    public FamilyTreeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addInfoTf = new javax.swing.JTextArea();
        addNameTf = new javax.swing.JTextField();
        addNameBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addInfoBtn = new javax.swing.JButton();
        lMessage = new javax.swing.JLabel();
        newFolder = new javax.swing.JTextField();
        newFolderBtn = new javax.swing.JButton();
        addNameLbl = new javax.swing.JLabel();
        newFolderLbl = new javax.swing.JLabel();
        mainLabelLbl = new javax.swing.JLabel();
        deleteLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        infoLbl = new javax.swing.JLabel();
        lmessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        familyMenu = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addInfoTf.setColumns(20);
        addInfoTf.setRows(5);
        jScrollPane2.setViewportView(addInfoTf);

        addNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNameTfActionPerformed(evt);
            }
        });

        addNameBtn.setText(">");
        addNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNameBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("X");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        addInfoBtn.setText(">>>");

        lMessage.setForeground(new java.awt.Color(255, 0, 0));

        newFolderBtn.setText(">>");
        newFolderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFolderBtnActionPerformed(evt);
            }
        });

        addNameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addNameLbl.setText("Add a new child");

        newFolderLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        newFolderLbl.setText("Add a new grandchild");

        mainLabelLbl.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        mainLabelLbl.setForeground(new java.awt.Color(255, 0, 0));
        mainLabelLbl.setText("NEW FAMILY TREE");

        deleteLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        deleteLbl.setText("Delete");

        infoLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        infoLbl.setText("Add information of member ");

        lmessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lMessage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(addNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(64, 64, 64))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(infoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(addInfoBtn))
                            .addComponent(newFolderBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addNameBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lmessage)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(mainLabelLbl)
                            .addGap(79, 79, 79))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(newFolderLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(newFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(mainLabelLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNameBtn)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newFolderLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFolderBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInfoBtn)
                    .addComponent(jLabel1)
                    .addComponent(infoLbl))
                .addGap(11, 11, 11)
                .addComponent(lMessage)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(deleteLbl)
                    .addComponent(lmessage))
                .addGap(22, 22, 22))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Great Grandfather");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Child One");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Grand Child");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Grand Child");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Child Two");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Grand Child");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Grand Child");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Child Three");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Grand Child");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Grand Child");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        familyMenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        familyMenu.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                familyMenuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(familyMenu);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNameTfActionPerformed

    private void addNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNameBtnActionPerformed
       
        DefaultTreeModel model = (DefaultTreeModel) familyMenu.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        
        if (addNameTf.getText().trim().equals ("")) {
	root.add(new DefaultMutableTreeNode (addNameTf.getText()));
	model.reload();
	
} else {
	lMessage.setText("You Must Enter A Name");
}
    }//GEN-LAST:event_addNameBtnActionPerformed

    private void newFolderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFolderBtnActionPerformed
       
       
    }//GEN-LAST:event_newFolderBtnActionPerformed

    private void familyMenuValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_familyMenuValueChanged
        // TODO add your handling code here:
     
        
        
    }//GEN-LAST:event_familyMenuValueChanged

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
       lMessage.setText("");
       DefaultTreeModel model = (DefaultTreeModel) familyMenu.getModel();
       DefaultTreeModel selectedNode = (DefaultTreeModel) familyMenu.getLastSelectedPathComponent();
       
       if (selectedNode.isLeaf(model)) {
       
           model.removeNodeFromParent((MutableTreeNode) selectedNode);
           
           
       } else {
       
		if (selectedNode!=null) {
		
		lMessage.setText ("Please select something to delete");
                }
       }
    
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilyTreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilyTreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilyTreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilyTreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilyTreeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInfoBtn;
    private javax.swing.JTextArea addInfoTf;
    private javax.swing.JButton addNameBtn;
    private javax.swing.JLabel addNameLbl;
    private javax.swing.JTextField addNameTf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel deleteLbl;
    private javax.swing.JTree familyMenu;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lMessage;
    private javax.swing.JLabel lmessage;
    private javax.swing.JLabel mainLabelLbl;
    private javax.swing.JTextField newFolder;
    private javax.swing.JButton newFolderBtn;
    private javax.swing.JLabel newFolderLbl;
    // End of variables declaration//GEN-END:variables
}
